# Generated by Django 4.2 on 2023-05-24 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User_info",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        max_length=32, unique=True, verbose_name="username"
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "user_register",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="register_time"
                    ),
                ),
            ],
            options={
                "db_table": "user",
            },
        ),
    ]
